// Code generated by Slice Machine. Adapted to eagerly load critical Hero slice.

import dynamic from "next/dynamic";
import Hero from "./Hero";

export const components = {
  before_after_slider: dynamic(() => import("./BeforeAfterSlider")),
  branches_portal: dynamic(() => import("./BranchesPortal")),
  card_stack: dynamic(() => import("./CardStack")),
  expandable_rows: dynamic(() => import("./ExpandableRows")),
  hero: Hero, // Eager load for immediate above-the-fold render
  large_text: dynamic(() => import("./LargeHeading")),
  media: dynamic(() => import("./Media")),
  media_swiper: dynamic(() => import("./MediaSwiper")),
  media_text: dynamic(() => import("./MediaText")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  numbered_cards: dynamic(() => import("./NumberedCards")),
  results: dynamic(() => import("./Results")),
  rich_text: dynamic(() => import("./RichText")),
  text_slider: dynamic(() => import("./TextSlider")),
  work_media: dynamic(() => import("./WorkMedia")),
};
